#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Run the APIM smoke test locally via JMeter.

.DESCRIPTION
  Runs apim-load-test.jmx against the APIM gateway endpoint and writes results
  to load_tests/scripts/jmeter/output/apim-smoke-test/<timestamp>/.

  Traffic path (local JMeter):
    JMeter (local) → [VPN/jumpbox required] → APIM Internal VNet → AI Foundry

  NOTE: APIM is deployed in Internal VNet mode. This test only works if you
  have VPN access to the Azure VNet or are running from the ACI jumpbox.
  For public-facing tests that work without VPN, use:
    run_jmeter_appgw-smoke-test.ps1 (routes traffic through App Gateway WAF)

.NOTES
  Prerequisites:
    - JMeter 5.6+ on PATH ('jmeter' binary)
    - az login completed
    - azd provision completed
    - VPN or ACI jumpbox access to reach APIM internal VNet endpoint
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$TEST_NAME = 'apim-smoke-test'

# ── Paths ────────────────────────────────────────────────────────────────────────
$repoRoot  = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
$jmxPath   = Join-Path $repoRoot 'load_tests' 'definitions' 'apim-load-test.jmx'
$outputDir = Join-Path $PSScriptRoot 'output' $TEST_NAME (Get-Date -Format 'yyyyMMdd-HHmmss')

# ── Step 1: Verify JMeter is on PATH ────────────────────────────────────────────
Write-Host ""
Write-Host "=== Step 1: Verify JMeter is available ===" -ForegroundColor Cyan

$jmeterCmd = Get-Command jmeter -ErrorAction SilentlyContinue
if (-not $jmeterCmd) {
    Write-Error "JMeter not found on PATH.`nInstall JMeter 5.6+ and ensure 'jmeter' (or 'jmeter.bat' on Windows) is on your PATH."
}
Write-Host "  JMeter: $($jmeterCmd.Source)" -ForegroundColor Green

# ── Step 2: Resolve environment ──────────────────────────────────────────────────
Write-Host ""
Write-Host "=== Step 2: Resolve environment ===" -ForegroundColor Cyan

. "$PSScriptRoot/../../../scripts/_resolve-env.ps1"

$APIM_HOSTNAME = "$APIM_NAME.azure-api.net"
Write-Host "  Resource group : $RG" -ForegroundColor Green
Write-Host "  APIM hostname  : $APIM_HOSTNAME" -ForegroundColor Green
Write-Host ""
Write-Host "  NOTE: APIM is Internal VNet — ensure you have VPN access or run from the ACI jumpbox." -ForegroundColor Yellow

# ── Step 3: Fetch APIM subscription keys ────────────────────────────────────────
Write-Host ""
Write-Host "=== Step 3: Fetch APIM subscription keys ===" -ForegroundColor Cyan

$BRONZE_KEY = (az rest --method POST `
    --uri "https://management.azure.com/subscriptions/$SUB_ID/resourceGroups/$RG/providers/Microsoft.ApiManagement/service/$APIM_NAME/subscriptions/app-branch-advisor/listSecrets?api-version=2022-08-01" `
    2>$null | ConvertFrom-Json).primaryKey

$SILVER_KEY = (az rest --method POST `
    --uri "https://management.azure.com/subscriptions/$SUB_ID/resourceGroups/$RG/providers/Microsoft.ApiManagement/service/$APIM_NAME/subscriptions/app-aml-screening/listSecrets?api-version=2022-08-01" `
    2>$null | ConvertFrom-Json).primaryKey

if (-not $BRONZE_KEY) { Write-Error "Failed to fetch Bronze key for 'app-branch-advisor'." }
if (-not $SILVER_KEY) { Write-Error "Failed to fetch Silver key for 'app-aml-screening'." }

Write-Host "  Bronze key (app-branch-advisor) : $($BRONZE_KEY.Substring(0,8))..." -ForegroundColor Green
Write-Host "  Silver key (app-aml-screening)  : $($SILVER_KEY.Substring(0,8))..." -ForegroundColor Green

# ── Step 4: Prepare output directory ────────────────────────────────────────────
Write-Host ""
Write-Host "=== Step 4: Prepare output directory ===" -ForegroundColor Cyan

New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
$jtlPath   = Join-Path $outputDir 'results.jtl'
$reportDir = Join-Path $outputDir 'html-report'

Write-Host "  Output: $outputDir" -ForegroundColor Green

# ── Step 5: Write user.properties (never committed — contains live keys) ─────────
$userPropsPath = Join-Path $env:TEMP 'jmeter-apim-smoke-user.properties'
@"
# JMeter user properties for apim-smoke-test
# Generated by run_jmeter_apim-smoke-test.ps1 — DO NOT COMMIT
APIM_HOSTNAME=$APIM_HOSTNAME
API_VERSION=2024-10-21
BRONZE_KEY=$BRONZE_KEY
SILVER_KEY=$SILVER_KEY
"@ | Set-Content -Path $userPropsPath -Encoding utf8

# TLS: trust-all (no App Gateway cert to validate for the direct APIM path)
$env:JVM_ARGS = '-Djavax.net.ssl.trustStore=NONE -Dhttps.use.cached.ssl.context=false'

# ── Step 6: Run JMeter ───────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=== Step 5: Run JMeter ===" -ForegroundColor Cyan
Write-Host "  JMX    : $jmxPath"
Write-Host "  Output : $outputDir"
Write-Host ""

jmeter -n `
    -t $jmxPath `
    -q $userPropsPath `
    -Jsummariser.interval=10 `
    -l $jtlPath `
    -e -o $reportDir

$exitCode = $LASTEXITCODE
$env:JVM_ARGS = ''
Remove-Item $userPropsPath -Force -ErrorAction SilentlyContinue

# ── Step 7: Report output location ───────────────────────────────────────────────
Write-Host ""
if ($exitCode -eq 0) {
    Write-Host "=== Test complete ===" -ForegroundColor Green
} else {
    Write-Host "=== JMeter exited with code $exitCode ===" -ForegroundColor Yellow
}
Write-Host "  Results  : $jtlPath"
Write-Host "  Report   : $reportDir\index.html"
Write-Host ""
Write-Host "  Open report:"
Write-Host "    Start-Process '$reportDir\index.html'"
Write-Host ""

exit $exitCode
