// main.bicep — azd entry point
// Orchestrates all infrastructure modules.
//
// `azd provision` creates EVERYTHING — no pre-existing resources required.
//
// Provision order:
//   1. networking          (VNet + subnets)
//   2. supportingInfra     (Log Analytics + Key Vault)
//   3. foundryAccounts     (2x AIServices — outputs feed apim-gateway)
//   4. apimGateway         (depends on foundry + networking + supportingInfra outputs)
//   5. wafAppGwPrimary     (East US — only if sslCertKeyVaultSecretId is set)
//   6. wafAppGwSecondary   (West US — optional, requires secondary VNet params)
//   7. kvCertRbacPrimary   (KV RBAC for App GW identity — conditional)
//   8. foundryApimRbac     (Cognitive Services User for APIM identity)
//   9. eventGridAutomation (Function App + Event Grid)
//  10. grafana             (Managed Grafana)

targetScope = 'subscription'

// ---------------------------------------------------------------------------
// Parameters — all have defaults so `azd provision` works without prompts.
// Override via `azd env set <NAME> <value>` before provisioning.
// ---------------------------------------------------------------------------

@description('Primary Azure region — resource group, APIM, networking, and supporting infra')
@allowed([
  'eastus'
  'eastus2'
  'westus'
  'westus2'
  'westus3'
  'centralus'
  'northcentralus'
  'southcentralus'
  'uksouth'
  'ukwest'
  'northeurope'
  'westeurope'
  'francecentral'
  'germanywestcentral'
  'norwayeast'
  'swedencentral'
  'switzerlandnorth'
  'australiaeast'
  'japaneast'
  'koreacentral'
  'southeastasia'
  'eastasia'
  'canadacentral'
  'brazilsouth'
])
param location string = 'eastus'

@description('Secondary Azure region — Foundry failover account and optional secondary App Gateway')
@allowed([
  'eastus'
  'eastus2'
  'westus'
  'westus2'
  'westus3'
  'centralus'
  'northcentralus'
  'southcentralus'
  'uksouth'
  'ukwest'
  'northeurope'
  'westeurope'
  'francecentral'
  'germanywestcentral'
  'norwayeast'
  'swedencentral'
  'switzerlandnorth'
  'australiaeast'
  'japaneast'
  'koreacentral'
  'southeastasia'
  'eastasia'
  'canadacentral'
  'brazilsouth'
])
param secondaryLocation string = 'westus'

@description('Environment tag — controls resource naming (e.g. dev, staging, prod, or your azd env name)')
param environment string = 'dev'

@description('Short prefix used in all resource names, e.g. "contoso" → apim name becomes "contoso-ai"')
param companyPrefix string = 'contoso'

// ---------------------------------------------------------------------------
// Optional: Azure OpenAI (legacy backend — Foundry AIServices is the primary path)
// Leave blank if you are using only the Foundry AIServices accounts created by this template.
// ---------------------------------------------------------------------------

@description('Azure OpenAI resource name (leave blank to use only Foundry AIServices accounts)')
param openaiResourceName string = ''

@secure()
@description('Azure OpenAI API key (leave blank if openaiResourceName is empty)')
param openaiApiKey string = ''

// ---------------------------------------------------------------------------
// Optional: Foundry developer access
// ---------------------------------------------------------------------------

@description('Entra ID Object IDs of individual developers to grant Cognitive Services User access on both Foundry accounts. Leave [] for no personal access.')
param developerObjectIds array = []

@description('Set to true only if your account has Owner or User Access Administrator on the subscription. Enables: Grafana → Monitoring Reader, KV admin role. Can be set after provisioning by someone with the right permissions.')
param deployRbac bool = false

// ---------------------------------------------------------------------------
// Optional: Grafana admin group
// ---------------------------------------------------------------------------

@description('Entra ID Object ID of the group or user to grant Grafana Admin. Leave blank to skip Grafana admin RBAC. Find it with: az ad group list --display-name "<name>" --query "[].id" -o tsv')
param itTeamObjectId string = ''

// ---------------------------------------------------------------------------
// Optional: App Gateway WAF (HTTPS termination layer in front of APIM)
// App Gateways are skipped if sslCertKeyVaultSecretId is blank.
// To add later: upload a PFX cert to the Key Vault created by this deployment,
// then set sslCertKeyVaultSecretId and re-run `azd provision`.
// ---------------------------------------------------------------------------

@secure()
@description('Override the auto-created self-signed cert with your own CA-signed certificate. Leave blank (default) to use the self-signed cert generated by Key Vault at provision time. Format: https://<kv>.vault.azure.net/secrets/<name>/<version>')
param sslCertKeyVaultSecretId string = ''

@description('APIM internal private IP in West US for secondary App Gateway. Leave blank to skip secondary region.')
param apimSecondaryPrivateIpAddress string = ''

// ---------------------------------------------------------------------------
// Resource group
// ---------------------------------------------------------------------------

resource rg 'Microsoft.Resources/resourceGroups@2022-09-01' = {
  name: 'rg-${companyPrefix}-ai-platform-${environment}'
  location: location
  tags: {
    environment: environment
    managedBy: 'azd'
    purpose: 'ai-as-a-service-platform'
    // Required: azd uses this tag to identify which resource group belongs to this environment
    'azd-env-name': environment
  }
}

// ---------------------------------------------------------------------------
// Module 1: Networking (VNet + subnets)
// Created first — APIM and App Gateway both depend on this VNet.
// ---------------------------------------------------------------------------

module networking 'networking.bicep' = {
  name: 'networking'
  scope: rg
  params: {
    location: location
    prefix: companyPrefix
    tags: {
      environment: environment
      managedBy: 'azd'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 2: Supporting infrastructure (Log Analytics Workspace + Key Vault)
// Created early so APIM can reference workspace ID and App GW can use the KV.
// ---------------------------------------------------------------------------

module supportingInfra 'supporting-infra.bicep' = {
  name: 'supporting-infra'
  scope: rg
  params: {
    location: location
    prefix: companyPrefix
    environment: environment
    deployRbac: deployRbac
    adminObjectId: itTeamObjectId
    tags: {
      environment: environment
      managedBy: 'azd'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 3: Foundry Accounts (2 × AIServices — primary East US, secondary West US)
// Hub workspaces are deprecated; Foundry now uses CognitiveServices/accounts.
// Deployed BEFORE apimGateway so its endpoint outputs can be passed in.
// ---------------------------------------------------------------------------

module foundryAccounts 'foundry-hub-project.bicep' = {
  name: 'foundry-accounts'
  scope: rg
  params: {
    accountPrefix: '${companyPrefix}-foundry'
    primaryLocation: location
    secondaryLocation: secondaryLocation
    developerObjectIds: developerObjectIds
    deployRbac: deployRbac
    vnetResourceId: networking.outputs.vnetId
    privateEndpointSubnetId: networking.outputs.privateEndpointSubnetId
  }
}

// ---------------------------------------------------------------------------
// Module 4: APIM Gateway
// Depends on foundryAccounts (endpoints), networking (VNet), supportingInfra (Log Analytics).
// ---------------------------------------------------------------------------

// APIM service names are GLOBALLY unique (they become {name}.azure-api.net).
// Common prefixes like 'contoso-ai' are already taken. Use uniqueString to generate
// a stable, per-subscription suffix that won't collide with other tenants.
var apimName = 'apim-${companyPrefix}-${substring(uniqueString(subscription().subscriptionId), 0, 8)}'

module apimGateway 'apim-gateway.bicep' = {
  name: 'apim-gateway'
  scope: rg
  params: {
    apimName: apimName
    openaiResourceName: openaiResourceName
    openaiApiKey: openaiApiKey
    appInsightsName: 'appi-${companyPrefix}-ai-${environment}'
    location: location
    logAnalyticsWorkspaceId: supportingInfra.outputs.logAnalyticsWorkspaceId
    vnetResourceId: networking.outputs.vnetId
    foundryPrimaryEndpoint: foundryAccounts.outputs.foundry1Endpoint
    foundrySecondaryEndpoint: foundryAccounts.outputs.foundry2Endpoint
  }
}

// ---------------------------------------------------------------------------
// Module 5a: App Gateway WAF v2 — East US (Primary)
// Skipped if no SSL cert is configured (sslCertKeyVaultSecretId is blank).
// To enable: upload a PFX cert to the Key Vault, then re-run azd provision.
// ---------------------------------------------------------------------------

// App Gateway deploys only if a cert URI is provided.
// - Without a cert, App Gateway is skipped (APIM still deploys and is fully functional).
// - To enable App Gateway WAF: run scripts/create-appgw-cert.ps1, then set
//   AZURE_SSL_CERT_KV_SECRET_ID and re-run azd provision.
var resolvedSslCertUri = sslCertKeyVaultSecretId
var deployAppGw = !empty(resolvedSslCertUri)

module wafAppGwPrimary 'waf-appgw.bicep' = if (deployAppGw) {
  name: 'waf-appgw-primary'
  scope: rg
  params: {
    location: location
    appGwName: 'agw-${companyPrefix}-ai-primary'
    vnetResourceId: networking.outputs.vnetId
    appGwSubnetName: 'snet-appgw-primary'
    apimInternalIpAddress: apimGateway.outputs.apimPrivateIpAddress
    apimGatewayHostname: '${apimName}.azure-api.net'
    sslCertKeyVaultSecretId: resolvedSslCertUri
    logAnalyticsWorkspaceId: supportingInfra.outputs.logAnalyticsWorkspaceId
    tags: {
      environment: environment
      managedBy: 'azd'
      region: 'primary'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 5b: App Gateway WAF v2 — West US (Secondary)
// Requires both sslCertKeyVaultSecretId AND apimSecondaryPrivateIpAddress.
// ---------------------------------------------------------------------------

var deploySecondaryAppGw = deployAppGw && !empty(apimSecondaryPrivateIpAddress)

module wafAppGwSecondary 'waf-appgw.bicep' = if (deploySecondaryAppGw) {
  name: 'waf-appgw-secondary'
  scope: rg
  params: {
    location: secondaryLocation
    appGwName: 'agw-${companyPrefix}-ai-secondary'
    vnetResourceId: networking.outputs.vnetId
    appGwSubnetName: 'snet-appgw-primary'
    apimInternalIpAddress: apimSecondaryPrivateIpAddress
    apimGatewayHostname: '${apimName}.azure-api.net'
    sslCertKeyVaultSecretId: resolvedSslCertUri
    logAnalyticsWorkspaceId: supportingInfra.outputs.logAnalyticsWorkspaceId
    tags: {
      environment: environment
      managedBy: 'azd'
      region: 'secondary'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 5c: Key Vault Certificate User RBAC for primary App Gateway UAMI
// Only deployed when App Gateway is deployed.
// ---------------------------------------------------------------------------

module kvCertRbacPrimary 'kv-cert-rbac.bicep' = if (deployAppGw) {
  name: 'kv-cert-rbac-primary'
  scope: rg
  params: {
    keyVaultName: supportingInfra.outputs.keyVaultName
    deployRbac: deployRbac
    #disable-next-line BCP318
    principalId: wafAppGwPrimary.outputs.appGwIdentityPrincipalId ?? ''
  }
}

module kvCertRbacSecondary 'kv-cert-rbac.bicep' = if (deploySecondaryAppGw) {
  name: 'kv-cert-rbac-secondary'
  scope: rg
  params: {
    keyVaultName: supportingInfra.outputs.keyVaultName
    deployRbac: deployRbac
    #disable-next-line BCP318
    principalId: wafAppGwSecondary.outputs.appGwIdentityPrincipalId ?? ''
  }
}

// ---------------------------------------------------------------------------
// Module 6: Foundry ↔ APIM RBAC
// Grants APIM managed identity 'Cognitive Services User' on both Foundry accounts.
// Separate module to avoid circular dependency.
// ---------------------------------------------------------------------------

module foundryApimRbac 'foundry-apim-rbac.bicep' = {
  name: 'foundry-apim-rbac'
  scope: rg
  params: {
    foundry1ResourceId: foundryAccounts.outputs.foundry1ResourceId
    foundry2ResourceId: foundryAccounts.outputs.foundry2ResourceId
    apimPrincipalId: apimGateway.outputs.apimManagedIdentityPrincipalId
    deployRbac: deployRbac
  }
}

// ---------------------------------------------------------------------------
@description('Set to true to deploy the Event Grid + Function App automation module. Uses Flex Consumption (FC1) plan — no Dynamic VM quota required.')
param deployFunctionApp bool = false

@description('Object ID of the principal running azd deploy. Granted Storage Blob Data Contributor so azd can upload the function zip. Set with: azd env set AZURE_DEPLOYING_USER_OBJECT_ID $(az ad signed-in-user show --query id -o tsv)')
param deployingUserObjectId string = ''

// Module 7: Event Grid + Function App automation
// ---------------------------------------------------------------------------

module eventGridAutomation 'event-grid-automation.bicep' = if (deployFunctionApp) {
  name: 'event-grid-automation'
  scope: rg
  params: {
    location: location
    apimResourceId: apimGateway.outputs.apimResourceId
    storageAccountName: 'st${companyPrefix}aifn${environment}'
    functionAppName: 'func-${companyPrefix}-ai-automation-${environment}'
    applicationInsightsConnectionString: apimGateway.outputs.appInsightsConnectionString
    deployingUserObjectId: deployingUserObjectId
    tags: {
      environment: environment
      managedBy: 'azd'
      // azd looks for azd-env-name on the resource group AND on individual service resources
      'azd-env-name': environment
    }
  }
}

// ---------------------------------------------------------------------------
// Module 8: Managed Grafana
// ---------------------------------------------------------------------------

module grafana 'managed-grafana.bicep' = {
  name: 'managed-grafana'
  scope: rg
  params: {
    location: location
    grafanaName: 'grafana-${companyPrefix}-ai-${environment}'
    itTeamObjectId: itTeamObjectId
    deployRbac: deployRbac
    tags: {
      environment: environment
      managedBy: 'azd'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 9: Azure Monitor Workbooks
// ---------------------------------------------------------------------------

module workbooks 'workbooks.bicep' = {
  name: 'workbooks'
  scope: rg
  params: {
    location: location
    logAnalyticsWorkspaceId: supportingInfra.outputs.logAnalyticsWorkspaceId
    tags: {
      environment: environment
      managedBy: 'azd'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 10: Jumpbox — Azure Container Instance (VNet-internal testing)
// Deploy with: azd env set AZURE_DEPLOY_JUMPBOX true
// Provides a Linux container inside the VNet for testing APIM (Internal mode).
// Installs JMeter 5.6, openai package. Access: az container exec -g <rg> -n aci-<prefix>-jumpbox --exec-command /bin/sh
// Uses ACI (no VM SKU needed) — avoids SkuNotAvailable errors in subscriptions
// with capacity restrictions.
// ---------------------------------------------------------------------------

@description('Deploy the ACI jumpbox for VNet-internal APIM testing. Set with: azd env set AZURE_DEPLOY_JUMPBOX true')
param deployJumpbox bool = false

module jumpbox 'jumpbox.bicep' = if (deployJumpbox) {
  name: 'jumpbox'
  scope: rg
  params: {
    location: location
    prefix: companyPrefix
    vnetResourceId: networking.outputs.vnetId
    tags: {
      environment: environment
      managedBy: 'azd'
      purpose: 'vnet-testing-jumpbox'
    }
  }
}

// ---------------------------------------------------------------------------
// Module 11: Azure Load Testing
// Deploy with: azd env set AZURE_DEPLOY_LOAD_TEST true
// Creates the ALT workspace only. The test definition (JMX, VNet injection,
// env vars) is wired up by the postprovision hook: scripts/configure-load-test.ps1
// ---------------------------------------------------------------------------

@description('Deploy the Azure Load Testing resource. Set with: azd env set AZURE_DEPLOY_LOAD_TEST true')
param deployLoadTest bool = false

module loadTesting 'load-testing.bicep' = if (deployLoadTest) {
  name: 'load-testing'
  scope: rg
  params: {
    location: location
    prefix: companyPrefix
    environment: environment
    vnetId: networking.outputs.vnetId
    tags: {
      environment: environment
      managedBy: 'azd'
    }
  }
}

// ---------------------------------------------------------------------------
// NOTE: Grafana managed identity → Monitoring Reader (subscription scope)
// This role assignment is not managed by Bicep to avoid conflicts with
// assignments Azure Managed Grafana creates automatically for its MSI.
// The assignment is verified/created once by scripts/configure-grafana-rbac.ps1
// or the azd postprovision hook if it does not already exist.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Outputs surfaced to azd (available via `azd env get-values`)
// ---------------------------------------------------------------------------

output APIM_GATEWAY_URL string = apimGateway.outputs.apimGatewayUrl
output APIM_PRINCIPAL_ID string = apimGateway.outputs.apimManagedIdentityPrincipalId
output APP_INSIGHTS_CONNECTION_STRING string = apimGateway.outputs.appInsightsConnectionString
output FOUNDRY_PRIMARY_ENDPOINT string = foundryAccounts.outputs.foundry1Endpoint
output FOUNDRY_SECONDARY_ENDPOINT string = foundryAccounts.outputs.foundry2Endpoint
output KEY_VAULT_NAME string = supportingInfra.outputs.keyVaultName
output KEY_VAULT_URI string = supportingInfra.outputs.keyVaultUri
output LOAD_TEST_SUBNET_ID string = networking.outputs.loadTestSubnetId
output GRAFANA_ENDPOINT string = grafana.outputs.grafanaEndpoint
// FUNCTION_APP_NAME output only available when deployFunctionApp=true. Enable with: azd env set AZURE_DEPLOY_FUNCTION_APP true
#disable-next-line BCP318
output FUNCTION_APP_NAME string = deployFunctionApp ? eventGridAutomation.outputs.functionAppName : ''
